SELECT * FROM messbox.messages;

CREATE TABLE messbox.messages(
   ID           INTEGER  NOT NULL PRIMARY KEY 
  ,RECIEVER_ID  INTEGER  NOT NULL
  ,PICTURE      VARCHAR(46) NOT NULL
  ,NAME         VARCHAR(17) NOT NULL
  ,COMPANY      VARCHAR(9) NOT NULL
  ,EMAIL        VARCHAR(28) NOT NULL
  ,PHONE        VARCHAR(17) NOT NULL
  ,ADDRESS      VARCHAR(62) NOT NULL
  ,MESSAGE      VARCHAR(493) NOT NULL
  ,MESSAGE_TIME VARCHAR(19) NOT NULL
);

INSERT INTO messbox.messages(ID,RECIEVER_ID,PICTURE,NAME,COMPANY,EMAIL,PHONE,ADDRESS,MESSAGE,MESSAGE_TIME,MESSAGE_READ) VALUES (1,1,'https://randomuser.me/api/portraits/men/20.jpg','Sonia Schneider','CANOPOLY','soniaschneider@canopoly.com','+1 (916) 571-2788','422 Mayfair Drive, Siglerville, Maryland, 1542','Laborum in ea deserunt amet. Aliqua sunt ut duis elit reprehenderit laborum consequat veniam. Lorem tempor excepteur aute non dolore in magna. Ipsum consectetur nostrud proident adipisicing ullamco qui sunt qui officia.','2018-12-19 03:30:22',0);
INSERT INTO messbox.messages(ID,RECIEVER_ID,PICTURE,NAME,COMPANY,EMAIL,PHONE,ADDRESS,MESSAGE,MESSAGE_TIME,MESSAGE_READ) VALUES (2,1,'https://randomuser.me/api/portraits/men/8.jpg','Mcdowell Thornton','TEMORAK','mcdowellthornton@temorak.com','+1 (961) 552-2159','251 Just Court, Marysville, Guam, 6736','Excepteur et cillum sit ut adipisicing ipsum fugiat velit. Labore dolor dolor velit irure sunt id anim sunt ut laborum ipsum cupidatat proident veniam. Culpa duis et adipisicing sint dolore eu pariatur cillum est consequat.','2018-12-29 06:45:36',0);
INSERT INTO messbox.messages(ID,RECIEVER_ID,PICTURE,NAME,COMPANY,EMAIL,PHONE,ADDRESS,MESSAGE,MESSAGE_TIME,MESSAGE_READ) VALUES (3,1,'https://randomuser.me/api/portraits/men/25.jpg','Dejesus Rios','PORTALINE','dejesusrios@portaline.com','+1 (894) 580-2591','263 Bank Street, Shawmut, New Jersey, 5042','Sit ut cillum velit sint officia duis esse ut nostrud commodo tempor. Magna est eu velit anim. Proident consequat excepteur in ut. Minim ipsum reprehenderit proident culpa.','2018-12-14 06:36:54',0);
INSERT INTO messbox.messages(ID,RECIEVER_ID,PICTURE,NAME,COMPANY,EMAIL,PHONE,ADDRESS,MESSAGE,MESSAGE_TIME,MESSAGE_READ) VALUES (4,1,'https://randomuser.me/api/portraits/men/73.jpg','Whitney Duffy','MATRIXITY','whitneyduffy@matrixity.com','+1 (908) 414-3454','998 Dorset Street, Nogal, Federated States Of Micronesia, 4869','Sunt laboris aliqua in ipsum. Ipsum occaecat qui amet duis amet ut aliqua do ipsum cupidatat fugiat ipsum. Incididunt do eiusmod exercitation cillum irure nulla ut veniam sit aute enim ad. Occaecat amet fugiat fugiat deserunt velit excepteur excepteur labore duis eu labore sunt culpa.','2018-12-24 04:05:07',0);
INSERT INTO messbox.messages(ID,RECIEVER_ID,PICTURE,NAME,COMPANY,EMAIL,PHONE,ADDRESS,MESSAGE,MESSAGE_TIME,MESSAGE_READ) VALUES (5,1,'https://randomuser.me/api/portraits/men/24.jpg','Rosalinda Murphy','ZOLARITY','rosalindamurphy@zolarity.com','+1 (894) 530-3597','179 Irvington Place, Wolcott, Nebraska, 2574','Aliquip fugiat aute aute veniam qui pariatur magna tempor elit tempor enim amet tempor laboris. Eu labore deserunt consequat mollit et. Ut consequat magna elit eiusmod sit eiusmod cupidatat aute id do anim nulla. Enim nulla commodo reprehenderit et ipsum officia commodo exercitation cillum sint aliqua sunt reprehenderit non. Quis deserunt veniam sunt amet anim elit reprehenderit ad. Deserunt id elit ex amet incididunt ea minim duis. Cillum culpa tempor amet ipsum ut anim labore laboris.','2018-12-27 09:59:59',0);
INSERT INTO messbox.messages(ID,RECIEVER_ID,PICTURE,NAME,COMPANY,EMAIL,PHONE,ADDRESS,MESSAGE,MESSAGE_TIME,MESSAGE_READ) VALUES (6,1,'https://randomuser.me/api/portraits/men/68.jpg','Vega Shepherd','NORALI','vegashepherd@norali.com','+1 (868) 508-3248','603 Hinckley Place, Axis, Illinois, 9726','Proident voluptate excepteur consequat eu dolor veniam mollit excepteur. In ad non reprehenderit proident eu qui. Non nostrud est laborum qui et ea.','2018-12-29 04:26:54',0);
INSERT INTO messbox.messages(ID,RECIEVER_ID,PICTURE,NAME,COMPANY,EMAIL,PHONE,ADDRESS,MESSAGE,MESSAGE_TIME,MESSAGE_READ) VALUES (7,1,'https://randomuser.me/api/portraits/men/79.jpg','Lizzie Ellis','XUMONK','lizzieellis@xumonk.com','+1 (967) 523-3472','946 Amherst Street, Delco, Washington, 4809','Anim ut est aliqua duis anim velit ipsum laborum laborum officia sit. Ex minim minim voluptate ad mollit velit ipsum pariatur do fugiat ullamco ex velit. Esse non consequat culpa sint non eiusmod culpa pariatur.','2018-12-21 12:48:11',0);

INSERT INTO messbox.messages(ID,RECIEVER_ID,PICTURE,NAME,COMPANY,EMAIL,PHONE,ADDRESS,MESSAGE,MESSAGE_TIME,MESSAGE_READ) VALUES (8,2,'https://randomuser.me/api/portraits/men/20.jpg','Sonia Schneider','CANOPOLY','soniaschneider@canopoly.com','+1 (916) 571-2788','422 Mayfair Drive, Siglerville, Maryland, 1542','Laborum in ea deserunt amet. Aliqua sunt ut duis elit reprehenderit laborum consequat veniam. Lorem tempor excepteur aute non dolore in magna. Ipsum consectetur nostrud proident adipisicing ullamco qui sunt qui officia.','2018-12-19 03:30:22',0);
INSERT INTO messbox.messages(ID,RECIEVER_ID,PICTURE,NAME,COMPANY,EMAIL,PHONE,ADDRESS,MESSAGE,MESSAGE_TIME,MESSAGE_READ) VALUES (9,2,'https://randomuser.me/api/portraits/men/8.jpg','Mcdowell Thornton','TEMORAK','mcdowellthornton@temorak.com','+1 (961) 552-2159','251 Just Court, Marysville, Guam, 6736','Excepteur et cillum sit ut adipisicing ipsum fugiat velit. Labore dolor dolor velit irure sunt id anim sunt ut laborum ipsum cupidatat proident veniam. Culpa duis et adipisicing sint dolore eu pariatur cillum est consequat.','2018-12-29 06:45:36',0);
INSERT INTO messbox.messages(ID,RECIEVER_ID,PICTURE,NAME,COMPANY,EMAIL,PHONE,ADDRESS,MESSAGE,MESSAGE_TIME,MESSAGE_READ) VALUES (10,2,'https://randomuser.me/api/portraits/men/25.jpg','Dejesus Rios','PORTALINE','dejesusrios@portaline.com','+1 (894) 580-2591','263 Bank Street, Shawmut, New Jersey, 5042','Sit ut cillum velit sint officia duis esse ut nostrud commodo tempor. Magna est eu velit anim. Proident consequat excepteur in ut. Minim ipsum reprehenderit proident culpa.','2018-12-14 06:36:54',0);
INSERT INTO messbox.messages(ID,RECIEVER_ID,PICTURE,NAME,COMPANY,EMAIL,PHONE,ADDRESS,MESSAGE,MESSAGE_TIME,MESSAGE_READ) VALUES (11,2,'https://randomuser.me/api/portraits/men/73.jpg','Whitney Duffy','MATRIXITY','whitneyduffy@matrixity.com','+1 (908) 414-3454','998 Dorset Street, Nogal, Federated States Of Micronesia, 4869','Sunt laboris aliqua in ipsum. Ipsum occaecat qui amet duis amet ut aliqua do ipsum cupidatat fugiat ipsum. Incididunt do eiusmod exercitation cillum irure nulla ut veniam sit aute enim ad. Occaecat amet fugiat fugiat deserunt velit excepteur excepteur labore duis eu labore sunt culpa.','2018-12-24 04:05:07',0);
INSERT INTO messbox.messages(ID,RECIEVER_ID,PICTURE,NAME,COMPANY,EMAIL,PHONE,ADDRESS,MESSAGE,MESSAGE_TIME,MESSAGE_READ) VALUES (12,2,'https://randomuser.me/api/portraits/men/24.jpg','Rosalinda Murphy','ZOLARITY','rosalindamurphy@zolarity.com','+1 (894) 530-3597','179 Irvington Place, Wolcott, Nebraska, 2574','Aliquip fugiat aute aute veniam qui pariatur magna tempor elit tempor enim amet tempor laboris. Eu labore deserunt consequat mollit et. Ut consequat magna elit eiusmod sit eiusmod cupidatat aute id do anim nulla. Enim nulla commodo reprehenderit et ipsum officia commodo exercitation cillum sint aliqua sunt reprehenderit non. Quis deserunt veniam sunt amet anim elit reprehenderit ad. Deserunt id elit ex amet incididunt ea minim duis. Cillum culpa tempor amet ipsum ut anim labore laboris.','2018-12-27 09:59:59',0);
INSERT INTO messbox.messages(ID,RECIEVER_ID,PICTURE,NAME,COMPANY,EMAIL,PHONE,ADDRESS,MESSAGE,MESSAGE_TIME,MESSAGE_READ) VALUES (13,2,'https://randomuser.me/api/portraits/men/68.jpg','Vega Shepherd','NORALI','vegashepherd@norali.com','+1 (868) 508-3248','603 Hinckley Place, Axis, Illinois, 9726','Proident voluptate excepteur consequat eu dolor veniam mollit excepteur. In ad non reprehenderit proident eu qui. Non nostrud est laborum qui et ea.','2018-12-29 04:26:54',0);
INSERT INTO messbox.messages(ID,RECIEVER_ID,PICTURE,NAME,COMPANY,EMAIL,PHONE,ADDRESS,MESSAGE,MESSAGE_TIME,MESSAGE_READ) VALUES (14,2,'https://randomuser.me/api/portraits/men/79.jpg','Lizzie Ellis','XUMONK','lizzieellis@xumonk.com','+1 (967) 523-3472','946 Amherst Street, Delco, Washington, 4809','Anim ut est aliqua duis anim velit ipsum laborum laborum officia sit. Ex minim minim voluptate ad mollit velit ipsum pariatur do fugiat ullamco ex velit. Esse non consequat culpa sint non eiusmod culpa pariatur.','2018-12-21 12:48:11',0);

INSERT INTO messbox.messages(ID,RECIEVER_ID,PICTURE,NAME,COMPANY,EMAIL,PHONE,ADDRESS,MESSAGE,MESSAGE_TIME,MESSAGE_READ) VALUES (15,3,'https://randomuser.me/api/portraits/men/20.jpg','Sonia Schneider','CANOPOLY','soniaschneider@canopoly.com','+1 (916) 571-2788','422 Mayfair Drive, Siglerville, Maryland, 1542','Laborum in ea deserunt amet. Aliqua sunt ut duis elit reprehenderit laborum consequat veniam. Lorem tempor excepteur aute non dolore in magna. Ipsum consectetur nostrud proident adipisicing ullamco qui sunt qui officia.','2018-12-19 03:30:22',0);
INSERT INTO messbox.messages(ID,RECIEVER_ID,PICTURE,NAME,COMPANY,EMAIL,PHONE,ADDRESS,MESSAGE,MESSAGE_TIME,MESSAGE_READ) VALUES (16,3,'https://randomuser.me/api/portraits/men/8.jpg','Mcdowell Thornton','TEMORAK','mcdowellthornton@temorak.com','+1 (961) 552-2159','251 Just Court, Marysville, Guam, 6736','Excepteur et cillum sit ut adipisicing ipsum fugiat velit. Labore dolor dolor velit irure sunt id anim sunt ut laborum ipsum cupidatat proident veniam. Culpa duis et adipisicing sint dolore eu pariatur cillum est consequat.','2018-12-29 06:45:36',0);
INSERT INTO messbox.messages(ID,RECIEVER_ID,PICTURE,NAME,COMPANY,EMAIL,PHONE,ADDRESS,MESSAGE,MESSAGE_TIME,MESSAGE_READ) VALUES (17,3,'https://randomuser.me/api/portraits/men/25.jpg','Dejesus Rios','PORTALINE','dejesusrios@portaline.com','+1 (894) 580-2591','263 Bank Street, Shawmut, New Jersey, 5042','Sit ut cillum velit sint officia duis esse ut nostrud commodo tempor. Magna est eu velit anim. Proident consequat excepteur in ut. Minim ipsum reprehenderit proident culpa.','2018-12-14 06:36:54',0);
INSERT INTO messbox.messages(ID,RECIEVER_ID,PICTURE,NAME,COMPANY,EMAIL,PHONE,ADDRESS,MESSAGE,MESSAGE_TIME,MESSAGE_READ) VALUES (18,3,'https://randomuser.me/api/portraits/men/73.jpg','Whitney Duffy','MATRIXITY','whitneyduffy@matrixity.com','+1 (908) 414-3454','998 Dorset Street, Nogal, Federated States Of Micronesia, 4869','Sunt laboris aliqua in ipsum. Ipsum occaecat qui amet duis amet ut aliqua do ipsum cupidatat fugiat ipsum. Incididunt do eiusmod exercitation cillum irure nulla ut veniam sit aute enim ad. Occaecat amet fugiat fugiat deserunt velit excepteur excepteur labore duis eu labore sunt culpa.','2018-12-24 04:05:07',0);
INSERT INTO messbox.messages(ID,RECIEVER_ID,PICTURE,NAME,COMPANY,EMAIL,PHONE,ADDRESS,MESSAGE,MESSAGE_TIME,MESSAGE_READ) VALUES (19,3,'https://randomuser.me/api/portraits/men/24.jpg','Rosalinda Murphy','ZOLARITY','rosalindamurphy@zolarity.com','+1 (894) 530-3597','179 Irvington Place, Wolcott, Nebraska, 2574','Aliquip fugiat aute aute veniam qui pariatur magna tempor elit tempor enim amet tempor laboris. Eu labore deserunt consequat mollit et. Ut consequat magna elit eiusmod sit eiusmod cupidatat aute id do anim nulla. Enim nulla commodo reprehenderit et ipsum officia commodo exercitation cillum sint aliqua sunt reprehenderit non. Quis deserunt veniam sunt amet anim elit reprehenderit ad. Deserunt id elit ex amet incididunt ea minim duis. Cillum culpa tempor amet ipsum ut anim labore laboris.','2018-12-27 09:59:59',0);
INSERT INTO messbox.messages(ID,RECIEVER_ID,PICTURE,NAME,COMPANY,EMAIL,PHONE,ADDRESS,MESSAGE,MESSAGE_TIME,MESSAGE_READ) VALUES (20,3,'https://randomuser.me/api/portraits/men/68.jpg','Vega Shepherd','NORALI','vegashepherd@norali.com','+1 (868) 508-3248','603 Hinckley Place, Axis, Illinois, 9726','Proident voluptate excepteur consequat eu dolor veniam mollit excepteur. In ad non reprehenderit proident eu qui. Non nostrud est laborum qui et ea.','2018-12-29 04:26:54',0);
INSERT INTO messbox.messages(ID,RECIEVER_ID,PICTURE,NAME,COMPANY,EMAIL,PHONE,ADDRESS,MESSAGE,MESSAGE_TIME,MESSAGE_READ) VALUES (21,3,'https://randomuser.me/api/portraits/men/79.jpg','Lizzie Ellis','XUMONK','lizzieellis@xumonk.com','+1 (967) 523-3472','946 Amherst Street, Delco, Washington, 4809','Anim ut est aliqua duis anim velit ipsum laborum laborum officia sit. Ex minim minim voluptate ad mollit velit ipsum pariatur do fugiat ullamco ex velit. Esse non consequat culpa sint non eiusmod culpa pariatur.','2018-12-21 12:48:11',0);

INSERT INTO messbox.messages(ID,RECIEVER_ID,PICTURE,NAME,COMPANY,EMAIL,PHONE,ADDRESS,MESSAGE,MESSAGE_TIME,MESSAGE_READ) VALUES (22,4,'https://randomuser.me/api/portraits/men/20.jpg','Sonia Schneider','CANOPOLY','soniaschneider@canopoly.com','+1 (916) 571-2788','422 Mayfair Drive, Siglerville, Maryland, 1542','Laborum in ea deserunt amet. Aliqua sunt ut duis elit reprehenderit laborum consequat veniam. Lorem tempor excepteur aute non dolore in magna. Ipsum consectetur nostrud proident adipisicing ullamco qui sunt qui officia.','2018-12-19 03:30:22',0);
INSERT INTO messbox.messages(ID,RECIEVER_ID,PICTURE,NAME,COMPANY,EMAIL,PHONE,ADDRESS,MESSAGE,MESSAGE_TIME,MESSAGE_READ) VALUES (23,4,'https://randomuser.me/api/portraits/men/8.jpg','Mcdowell Thornton','TEMORAK','mcdowellthornton@temorak.com','+1 (961) 552-2159','251 Just Court, Marysville, Guam, 6736','Excepteur et cillum sit ut adipisicing ipsum fugiat velit. Labore dolor dolor velit irure sunt id anim sunt ut laborum ipsum cupidatat proident veniam. Culpa duis et adipisicing sint dolore eu pariatur cillum est consequat.','2018-12-29 06:45:36',0);
INSERT INTO messbox.messages(ID,RECIEVER_ID,PICTURE,NAME,COMPANY,EMAIL,PHONE,ADDRESS,MESSAGE,MESSAGE_TIME,MESSAGE_READ) VALUES (24,4,'https://randomuser.me/api/portraits/men/25.jpg','Dejesus Rios','PORTALINE','dejesusrios@portaline.com','+1 (894) 580-2591','263 Bank Street, Shawmut, New Jersey, 5042','Sit ut cillum velit sint officia duis esse ut nostrud commodo tempor. Magna est eu velit anim. Proident consequat excepteur in ut. Minim ipsum reprehenderit proident culpa.','2018-12-14 06:36:54',0);
INSERT INTO messbox.messages(ID,RECIEVER_ID,PICTURE,NAME,COMPANY,EMAIL,PHONE,ADDRESS,MESSAGE,MESSAGE_TIME,MESSAGE_READ) VALUES (25,4,'https://randomuser.me/api/portraits/men/73.jpg','Whitney Duffy','MATRIXITY','whitneyduffy@matrixity.com','+1 (908) 414-3454','998 Dorset Street, Nogal, Federated States Of Micronesia, 4869','Sunt laboris aliqua in ipsum. Ipsum occaecat qui amet duis amet ut aliqua do ipsum cupidatat fugiat ipsum. Incididunt do eiusmod exercitation cillum irure nulla ut veniam sit aute enim ad. Occaecat amet fugiat fugiat deserunt velit excepteur excepteur labore duis eu labore sunt culpa.','2018-12-24 04:05:07',0);
INSERT INTO messbox.messages(ID,RECIEVER_ID,PICTURE,NAME,COMPANY,EMAIL,PHONE,ADDRESS,MESSAGE,MESSAGE_TIME,MESSAGE_READ) VALUES (26,4,'https://randomuser.me/api/portraits/men/24.jpg','Rosalinda Murphy','ZOLARITY','rosalindamurphy@zolarity.com','+1 (894) 530-3597','179 Irvington Place, Wolcott, Nebraska, 2574','Aliquip fugiat aute aute veniam qui pariatur magna tempor elit tempor enim amet tempor laboris. Eu labore deserunt consequat mollit et. Ut consequat magna elit eiusmod sit eiusmod cupidatat aute id do anim nulla. Enim nulla commodo reprehenderit et ipsum officia commodo exercitation cillum sint aliqua sunt reprehenderit non. Quis deserunt veniam sunt amet anim elit reprehenderit ad. Deserunt id elit ex amet incididunt ea minim duis. Cillum culpa tempor amet ipsum ut anim labore laboris.','2018-12-27 09:59:59',0);
INSERT INTO messbox.messages(ID,RECIEVER_ID,PICTURE,NAME,COMPANY,EMAIL,PHONE,ADDRESS,MESSAGE,MESSAGE_TIME,MESSAGE_READ) VALUES (27,4,'https://randomuser.me/api/portraits/men/68.jpg','Vega Shepherd','NORALI','vegashepherd@norali.com','+1 (868) 508-3248','603 Hinckley Place, Axis, Illinois, 9726','Proident voluptate excepteur consequat eu dolor veniam mollit excepteur. In ad non reprehenderit proident eu qui. Non nostrud est laborum qui et ea.','2018-12-29 04:26:54',0);
INSERT INTO messbox.messages(ID,RECIEVER_ID,PICTURE,NAME,COMPANY,EMAIL,PHONE,ADDRESS,MESSAGE,MESSAGE_TIME,MESSAGE_READ) VALUES (28,4,'https://randomuser.me/api/portraits/men/79.jpg','Lizzie Ellis','XUMONK','lizzieellis@xumonk.com','+1 (967) 523-3472','946 Amherst Street, Delco, Washington, 4809','Anim ut est aliqua duis anim velit ipsum laborum laborum officia sit. Ex minim minim voluptate ad mollit velit ipsum pariatur do fugiat ullamco ex velit. Esse non consequat culpa sint non eiusmod culpa pariatur.','2018-12-21 12:48:11',0);

INSERT INTO messbox.messages(ID,RECIEVER_ID,PICTURE,NAME,COMPANY,EMAIL,PHONE,ADDRESS,MESSAGE,MESSAGE_TIME,MESSAGE_READ) VALUES (29,5,'https://randomuser.me/api/portraits/men/20.jpg','Sonia Schneider','CANOPOLY','soniaschneider@canopoly.com','+1 (916) 571-2788','422 Mayfair Drive, Siglerville, Maryland, 1542','Laborum in ea deserunt amet. Aliqua sunt ut duis elit reprehenderit laborum consequat veniam. Lorem tempor excepteur aute non dolore in magna. Ipsum consectetur nostrud proident adipisicing ullamco qui sunt qui officia.','2018-12-19 03:30:22',0);
INSERT INTO messbox.messages(ID,RECIEVER_ID,PICTURE,NAME,COMPANY,EMAIL,PHONE,ADDRESS,MESSAGE,MESSAGE_TIME,MESSAGE_READ) VALUES (30,5,'https://randomuser.me/api/portraits/men/8.jpg','Mcdowell Thornton','TEMORAK','mcdowellthornton@temorak.com','+1 (961) 552-2159','251 Just Court, Marysville, Guam, 6736','Excepteur et cillum sit ut adipisicing ipsum fugiat velit. Labore dolor dolor velit irure sunt id anim sunt ut laborum ipsum cupidatat proident veniam. Culpa duis et adipisicing sint dolore eu pariatur cillum est consequat.','2018-12-29 06:45:36',0);
INSERT INTO messbox.messages(ID,RECIEVER_ID,PICTURE,NAME,COMPANY,EMAIL,PHONE,ADDRESS,MESSAGE,MESSAGE_TIME,MESSAGE_READ) VALUES (31,5,'https://randomuser.me/api/portraits/men/25.jpg','Dejesus Rios','PORTALINE','dejesusrios@portaline.com','+1 (894) 580-2591','263 Bank Street, Shawmut, New Jersey, 5042','Sit ut cillum velit sint officia duis esse ut nostrud commodo tempor. Magna est eu velit anim. Proident consequat excepteur in ut. Minim ipsum reprehenderit proident culpa.','2018-12-14 06:36:54',0);
INSERT INTO messbox.messages(ID,RECIEVER_ID,PICTURE,NAME,COMPANY,EMAIL,PHONE,ADDRESS,MESSAGE,MESSAGE_TIME,MESSAGE_READ) VALUES (32,5,'https://randomuser.me/api/portraits/men/73.jpg','Whitney Duffy','MATRIXITY','whitneyduffy@matrixity.com','+1 (908) 414-3454','998 Dorset Street, Nogal, Federated States Of Micronesia, 4869','Sunt laboris aliqua in ipsum. Ipsum occaecat qui amet duis amet ut aliqua do ipsum cupidatat fugiat ipsum. Incididunt do eiusmod exercitation cillum irure nulla ut veniam sit aute enim ad. Occaecat amet fugiat fugiat deserunt velit excepteur excepteur labore duis eu labore sunt culpa.','2018-12-24 04:05:07',0);
INSERT INTO messbox.messages(ID,RECIEVER_ID,PICTURE,NAME,COMPANY,EMAIL,PHONE,ADDRESS,MESSAGE,MESSAGE_TIME,MESSAGE_READ) VALUES (33,5,'https://randomuser.me/api/portraits/men/24.jpg','Rosalinda Murphy','ZOLARITY','rosalindamurphy@zolarity.com','+1 (894) 530-3597','179 Irvington Place, Wolcott, Nebraska, 2574','Aliquip fugiat aute aute veniam qui pariatur magna tempor elit tempor enim amet tempor laboris. Eu labore deserunt consequat mollit et. Ut consequat magna elit eiusmod sit eiusmod cupidatat aute id do anim nulla. Enim nulla commodo reprehenderit et ipsum officia commodo exercitation cillum sint aliqua sunt reprehenderit non. Quis deserunt veniam sunt amet anim elit reprehenderit ad. Deserunt id elit ex amet incididunt ea minim duis. Cillum culpa tempor amet ipsum ut anim labore laboris.','2018-12-27 09:59:59',0);
INSERT INTO messbox.messages(ID,RECIEVER_ID,PICTURE,NAME,COMPANY,EMAIL,PHONE,ADDRESS,MESSAGE,MESSAGE_TIME,MESSAGE_READ) VALUES (34,5,'https://randomuser.me/api/portraits/men/68.jpg','Vega Shepherd','NORALI','vegashepherd@norali.com','+1 (868) 508-3248','603 Hinckley Place, Axis, Illinois, 9726','Proident voluptate excepteur consequat eu dolor veniam mollit excepteur. In ad non reprehenderit proident eu qui. Non nostrud est laborum qui et ea.','2018-12-29 04:26:54',0);
INSERT INTO messbox.messages(ID,RECIEVER_ID,PICTURE,NAME,COMPANY,EMAIL,PHONE,ADDRESS,MESSAGE,MESSAGE_TIME,MESSAGE_READ) VALUES (35,5,'https://randomuser.me/api/portraits/men/79.jpg','Lizzie Ellis','XUMONK','lizzieellis@xumonk.com','+1 (967) 523-3472','946 Amherst Street, Delco, Washington, 4809','Anim ut est aliqua duis anim velit ipsum laborum laborum officia sit. Ex minim minim voluptate ad mollit velit ipsum pariatur do fugiat ullamco ex velit. Esse non consequat culpa sint non eiusmod culpa pariatur.','2018-12-21 12:48:11',0);

